const UPDATE_TASK_BODY = "UPDATE_TASK_BODY";
const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";
const ADD_IN_WORK_TASK = "ADD_IN_WORK_TASK";
const ADD_ON_CHECK_TASK = "ADD_ON_CHECK_TASK";
const ADD_COMPLETED_TASK = "ADD_COMPLETED_TASK";
const GET_CURRENT_TASK = 'GET_CURRENT_TASK';

export {UPDATE_TASK_BODY, CHANGE_TASK_STATUS, ADD_IN_WORK_TASK, ADD_ON_CHECK_TASK, ADD_COMPLETED_TASK, GET_CURRENT_TASK};
